### ISSUE TITLE
Could you apply some tips on how to run this ?

### ISSUE THREAD

**Issue by monkeyking** [ChrisChV/3D-Laser-Scanner-with-Web-Camera#1]
Thanks for your devote .
But I just confused how does it work or how to run this .
TQ

**Comment by ChrisChV** [comment]
You need to connect a camera to your computer, a base that you can rotate (automaticly if you can) where you put the things you want to scan, and a red laser poiting to the thing in the base. You should put this things in this way:

![image](https://user-images.githubusercontent.com/11827305/49487718-b59e8f00-f811-11e8-9579-126a6b4f8bd7.png)

 You should compile the file "main.cpp" and run it in a total dark place and the base rotating. The output is a cloud of points that you can open with PCL. Here there is a video of the hardware of our proyect, but it's in Spanish:
https://www.youtube.com/watch?v=ONPTDkiC_aE

When I will have more time, I will write the Readme with this things more explained.

**Comment by monkeyking** [comment]
@ChrisChV Great Tk!
